CREATE TABLE "GCG_6701_Shipping"(
 "ORDER_NO" CHAR(7),
 "CUST_PO" CHAR(15),
 "ORDER_SORT" CHAR(20),
 "SHIPPED" CHAR(1),
 "ORDER_DATE" DATE,
 "ORDER_SUFFIX" CHAR(4),
 "SHIPPED_DATE" DATE,
 "NOTES" LONGVARCHAR );